Update Microsoft Azure OAuth guide
clerk/clerk-docs pull request #1135
Opened 2024-06-05 17:59 UTC by S3Prototype

wip

2024-06-07 13:08 UTC, S3Prototype commented on docs/authentication/saml/azure.mdx
> +description: Learn how to integrate Microsoft Azure Entra ID with Clerk using SAML SSO.
```suggestion
description: Learn how to allow users to sign into your Clerk app with their Microsoft account using SAML SSO.
```

2024-06-07 13:09 UTC, S3Prototype commented on docs/authentication/social-connections/microsoft.mdx
>  description: Learn how to set up social connection with Microsoft.
```suggestion
description: Learn how to allow users to sign into your Clerk app with their Microsoft account using OAuth.
```

2024-06-07 13:17 UTC, S3Prototype commented on docs/authentication/social-connections/microsoft.mdx
>  For production instances, you will need to generate your own Client ID and Client Secret using your Microsoft Azure account.
```suggestion
Adding social connection with Microsoft Azure to your app with Clerk only requires populating the **Client ID**, **Client Secret** and **Authorized redirect URI** in your instance settings.

Clerk uses preconfigured shared OAuth credentials and redirect URIs for development instances - no other configuration is needed. For production instances, you must generate your own **Client ID** and **Client Secret** as shown in the instructions in this guide.

```

2024-06-07 13:25 UTC, S3Prototype commented on docs/authentication/social-connections/microsoft.mdx
> +Adding social connection with Microsoft Azure to your app with Clerk only requires populating the **Client ID**, **Client Secret** and **Authorized redirect URI** in your instance settings.
```suggestion
Configuring this feature requires populating the **Client ID**, **Client Secret** and **Authorized redirect URI** in your Clerk app's settings.

```

2024-06-10 18:01 UTC, alexisintech requested changes

2024-06-11 18:37 UTC, alexisintech commented on docs/authentication/social-connections/microsoft.mdx
> +### Connect Entra ID app and get your redirect URI
```suggestion
### Connect your Entra ID app and get your redirect URI

```

2024-06-11 18:44 UTC, alexisintech commented on docs/authentication/social-connections/microsoft.mdx
> +For OAuth to function, Clerk requires an `id_token` from Microsoft Entra ID.
We mention `id_token` here but the user doesn't use this, do they? I'm not sure why we mention it.

We can just say something like "To connect your Clerk app to your Microsoft app, you must set the **Authorized redirect URI** in your Microsoft dashboard.

2024-06-11 18:51 UTC, alexisintech commented on docs/authentication/social-connections/microsoft.mdx
> +The simplest way to test your OAuth is to visit your Clerk application's account portal, which Clerk creates for all applications.
Two suggestions here based on where we want to say "out-of-the-box"

```suggestion
The simplest way to test your OAuth is to visit your Clerk application's [Account Portal](/docs/account-portal/overview), which is available for all Clerk applications out-of-the-box.

```

```suggestion
The simplest way to test your OAuth is to visit your Clerk application's [Account Portal](/docs/account-portal/overview), which is available out-of-the-box for all Clerk applications.

```

2024-06-17 15:29 UTC, alexisintech approved these changes

2024-06-18 17:28 UTC, merged