Added clarity for webhooks docs.
clerk/clerk-docs pull request #1170
Opened 2024-06-17 19:52 UTC by arti-bol

1. Fixed some grammar errors, added clarity.
2. Added a section on how to develop and test

2024-06-17 20:51 UTC, alexisintech requested changes
hey friend, I appreciate the grammar updates and I'll accept those, but we declined the addition of Beeceptor before, and are going to stick with our original decision.

2024-06-17 20:51 UTC, alexisintech commented on docs/integrations/webhooks/overview.mdx
> +## Webhook security
We prefer the action-oriented title!

```suggestion
## Protect your webhooks from abuse
```

2024-06-17 20:51 UTC, alexisintech commented on docs/integrations/webhooks/overview.mdx
> +4. Route requests to a localhost port like 3000 or 8080: Use the Beeceptor CLI to route requests to a localhost port for local testing.
Friend, we [declined this addition before](https://github.com/clerk/clerk-docs/pull/693) and are going to stick with our original decision of declining!

```suggestion
```

2024-06-18 07:54 UTC, arti-bol commented
Hi Alex, my bad about the repeat ask.  I have removed it, and only kept the grammer suggestions. Hope this is good now.

2024-06-18 15:33 UTC, alexisintech approved these changes

2024-06-18 15:33 UTC, merged