Replace dotenv with @next/env in neon guide
clerk/clerk-docs pull request #1211
Opened 2024-06-30 01:15 UTC by kevinzunigacuellar

> [!IMPORTANT]
> 🔎 Previews:
>
> -

### Explanation

This PR removes the usage of `dotenv` from the neon guide. While a small change, it favors the use of framework-specific utility libraries and reduces unnecessary dependencies, thus simplifying the overall setup.

### Changes Made

- Replaced `dotenv` with [`@next/env`](https://www.npmjs.com/package/@next/env) utility for loading environment variables.
- Added a check for `DATABASE_URL` in `drizzle.config.ts`.

2024-06-30 21:08 UTC, royanger requested changes
Thanks for the PR! This guide is suggesting to use the standard `.env.local` file to store environment variables, which Next has built-in support for. Let's remove `dotenv` and `next/env` altogether, keep in the second check for the DB URL.

2024-06-30 21:08 UTC, royanger commented on docs/integrations/databases/neon.mdx
> +      throw new Error("DATABASE_URL is not defined");
```suggestion
      throw new Error("DATABASE_URL must be a Neon postgres connection string");
```
Let's use consistent messaging.

2024-06-30 21:54 UTC, kevinzunigacuellar commented
> Let's remove `dotenv` and `next/env` altogether, keep in the second check for the DB URL.

Thanks for the review Roy

Unfortunately, removing `next/env` from the `drizzle.config` file will cause an error because the Drizzle ORM CLI doesn’t rely on the Next.js server to run scripts, so these variables won't be available at runtime.

While it is possible to remove `next/env` from `schema.ts`, it’s a common practice to load environment variables at this point for scripts that run outside the Next.js server context.

2024-07-01 06:16 UTC, royanger approved these changes

2024-07-01 06:16 UTC, merged

2024-07-01 13:26 UTC, kevinzunigacuellar commented
Thanks for the support @royanger 🎉