Refactor: Update order of lib managers in the CodeBlockTabs on the add-react-router reference page
clerk/clerk-docs pull request #1298
Opened 2024-07-19 19:35 UTC by kduprey

> [!IMPORTANT]
> 🔎 Previews:
>
> -

### Explanation:
In order to improve DX within our docs, the lib managers order should be consistent from page to page, to reduce confusion and maintain patterns across the docs.

### This PR:

- Update the add-react-router page codeblock options prop to have an array of `['npm', 'yarn', 'pnpm']` to match the same order as the previous React quick start guide's codeblock order

2024-07-19 21:45 UTC, royanger approved these changes
🚀

2024-07-22 12:35 UTC, LekoArts requested changes
When changing the `options` prop you'll also need to change the order of the code blocks inside the `CodeBlockTabs` component. When visiting the preview at https://clerk.com/docs/pr/1298/references/react/add-react-router you'll see that after selecting `yarn` you'll see the pnpm instructions.

Swap the two code blocks and it'll be fine 👍

2024-07-22 19:32 UTC, kduprey reviewed
Addressed in last commit

2024-07-22 19:53 UTC, alexisintech approved these changes

2024-07-22 19:55 UTC, merged