Added warning to top of Clerk as IDP/Oauth Provider that it does not return JWT
clerk/clerk-docs pull request #1300
Opened 2024-07-22 15:34 UTC by royanger

> [!IMPORTANT]
> 🔎 Previews:
>
> -

### Explanation: 

- Added a `warning` callout to the top of the pag.e

### This PR:

- Customers continue to the think the Clerk as OAuth provider features returns a JWT.

2024-07-22 19:57 UTC, alexisintech requested changes

2024-07-22 19:57 UTC, alexisintech commented on docs/advanced-usage/clerk-idp.mdx
> +> This feature will not return a Clerk JWT and does provide authentication. Please see the [FAQ](#how-can-the-access-tokens-obtained-from-the-token-url-be-used) below for more information.
did you mean "does not"

2024-07-22 22:48 UTC, royanger commented on docs/advanced-usage/clerk-idp.mdx
> +> This feature will not return a Clerk JWT and does provide authentication. Please see the [FAQ](#how-can-the-access-tokens-obtained-from-the-token-url-be-used) below for more information.
Yes. Its updated now.

2024-07-23 01:52 UTC, jescalan approved these changes

2024-07-23 03:59 UTC, merged