Rename Expo read-session-user-data doc; remove unused import
clerk/clerk-docs pull request #1359
Opened 2024-08-01 19:14 UTC by alexisintech

> [!IMPORTANT]
> 🔎 Previews:
>
> -

### Explanation:

### This PR:

-

2024-08-01 19:24 UTC, jescalan approved these changes

2024-08-01 19:24 UTC, jescalan requested changes
Actually hold up don't we now need to add a redirect for the old path

2024-08-02 15:53 UTC, alexisintech commented
> Actually hold up don't we now need to add a redirect for the old path

https://github.com/clerk/clerk/pull/549

2024-08-02 21:47 UTC, jescalan approved these changes
Approved contingent on redirect PR merging 😁

2024-08-06 17:54 UTC, merged