update email link custom flow guide
clerk/clerk-docs pull request #1433
Opened 2024-08-13 16:32 UTC by alexisintech

> [!IMPORTANT]
> 🔎 Previews:
>
> -

### Explanation:

https://linear.app/clerk/issue/DOCS-5240/httpsdocs-preview-702clerkpreviewcomdocscustom-flowsemail-links

### This PR:

-

2025-02-03 19:54 UTC, royanger commented
Let me know if you need me to test the code @alexisintech  -- I can't until Wed or Thurs this week.

2025-02-03 21:53 UTC, alexisintech commented
> Let me know if you need me to test the code @alexisintech -- I can't until Wed or Thurs this week.

yeah I would appreciate :) we've done all these custom flows together, so I trust you to test these out! 🫶

2025-02-07 06:53 UTC, royanger requested changes
I opened a linear for the `VerificationStatus` type, and have to followup about a client mismatch I was getting when I should not have been. Otherwise this looks pretty good.

2025-02-07 06:53 UTC, royanger commented on docs/custom-flows/email-links.mdx
> +          async function verify() {
This may need to check/handle `verified_switch_tab`. I didn't test enough to know though. Same for sign-in/verify/page.tsx

2025-02-07 06:53 UTC, royanger commented on docs/custom-flows/email-links.mdx
> +                setError(err.errors[0].longMessage)
This includes a general `console.log` that logs the `err` and then the `console.error` that logs the `longMessage` from `err`. This should have just one of these. Same for the `sign-in/page.tsx`

2025-02-07 06:53 UTC, royanger commented on docs/custom-flows/email-links.mdx
> +          if (verificationStatus === 'client_mismatch') {
I received `verify?__clerk_status=client_mismatch` with same computer/browser. I'm going to check with SDK tomorrow(Friday) about this.

2025-02-07 06:53 UTC, royanger commented on docs/custom-flows/email-links.mdx
> +  ### Email address verification flow
I get why this was added, but the more I think about it the more I don't love it. There are some nuances between the two. I think adding it made the info above a little weaker trying to talk about sign-up, sign-ins and adding email.

2025-02-07 20:23 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  1. Ensure that _only_ **Email address** is required. If **Phone number** and **Username** are enabled, ensure they are not required. Use the settings icon next to each option to verify if a setting
good feedback! i'll update the copy and add `name`

2025-02-07 20:26 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +          async function verify() {
what does it mean, like when would this come up? I used two different tabs and this never came up for me

2025-02-07 20:32 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  ## Enable email link verification
you have to enable an authentication option before you can configure the verification option

2025-02-07 20:43 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +                setError(err.errors[0].longMessage)
fixed them ! [7f1c1b0](https://github.com/clerk/clerk-docs/pull/1433/commits/7f1c1b0d37bc0eb95bd07995e476e7e9d66c9cf0)

2025-02-07 20:43 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  The flow for handling email links is the same across all use cases. You must:
updated the descriptions for each [7f1c1b0](https://github.com/clerk/clerk-docs/pull/1433/commits/7f1c1b0d37bc0eb95bd07995e476e7e9d66c9cf0)

2025-02-07 20:44 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  1. Because this guide focuses on email links, uncheck the box for **Email verification code**.
updated! [7f1c1b0](https://github.com/clerk/clerk-docs/pull/1433/commits/7f1c1b0d37bc0eb95bd07995e476e7e9d66c9cf0)

2025-02-07 20:44 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  [**Verification methods**](/docs/authentication/configuration/sign-up-sign-in-options#verification-methods) are different from [**authentication strategies**](/docs/authentication/configuration/sig
updated [7f1c1b0](https://github.com/clerk/clerk-docs/pull/1433/commits/7f1c1b0d37bc0eb95bd07995e476e7e9d66c9cf0)

2025-02-07 20:44 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  1. Ensure that _only_ **Email address** is required. If **Phone number** and **Username** are enabled, ensure they are not required. Use the settings icon next to each option to verify if a setting
updated [7f1c1b0](https://github.com/clerk/clerk-docs/pull/1433/commits/7f1c1b0d37bc0eb95bd07995e476e7e9d66c9cf0)

2025-02-07 21:08 UTC, royanger commented on docs/custom-flows/email-links.mdx
> +  ## Enable email link verification
I have Email enabled and required, and Email verification link enabled. This is while the Authentication strategies -> Email verification link is disabled.. I can even disable 'Sign-in' inside of the email settings modal. This enables email link for sign-up, but fully disallows it for sign-in (not that I'm recommending that of course).

2025-02-07 21:09 UTC, royanger commented on docs/custom-flows/email-links.mdx
> +          async function verify() {
I'm not sure off hand -- I didn't dig into it. That might be a question for SDK. I dropped my comment as I saw that was a possible status but wasn't mentioned or handled in the code.

2025-02-07 22:31 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  ## Enable email link verification
that's a backwards approach though. you'd have to enable email as an identifier. then you'd have to go into the settings cog, disable for sign-up, and then disable email code verification and enable email link verification.
we're gonna tailor this towards conventional practices - a user enables email as an identifier. they need to disable email code verification and enable email link verification.

2025-02-07 22:41 UTC, royanger commented on docs/custom-flows/email-links.mdx
> +  ## Enable email link verification
> that's a backwards approach though. you'd have to enable email as an identifier.

I'm not suggesting that at all. I am just suggesting swapping the order, because a developer is likely to want to consider sign-up(verification) and then (sign-in). 

The point I was making is that you do not need email link authentication enabled to setup email link verification, so that's not a limit in swapping the order here.

> a user enables email as an identifier. they need to disable email code verification and enable email link verification.

Yes, correct. Again, I'm not suggesting we don't do that.

2025-02-07 22:48 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  ## Enable email link verification
bear with me i'm just confused

2025-02-07 22:51 UTC, alexisintech commented on docs/custom-flows/email-links.mdx
> +  ## Enable email link verification
let's call on monday so you can just show me in a call what you're suggesting! because i think its getting lost over translation

2025-02-21 22:59 UTC, alexisintech commented
need to update https://clerk.com/docs/references/javascript/clerk#handle-email-link-verification:~:text=organization.id)-,handleEmailLinkVerification(),-Completes%20an%20email

2025-02-24 19:29 UTC, royanger approved these changes
🚀

2025-02-24 19:37 UTC, merged