Add changes for api version 2024-10-01
clerk/clerk-docs pull request #1717
Opened 2024-11-18 17:42 UTC by Nikpolik

> [!IMPORTANT]
> 🔎 Previews:
>
> -

### This PR:

- Adds the changes for our new api version `2024-10-01` in the appropriate list

### Checklist

- [x] I have clicked on "Files changed" and performed a thorough self-review
- [x] I have added the "deploy-preview" label and added the preview link(s) to this PR description
- [ ] All existing checks pass

2024-11-18 18:43 UTC, gkats reviewed
Looks good to me, thanks @Nikpolik!

2024-11-27 14:44 UTC, alexisintech commented on docs/backend-requests/versioning/available-versions.mdx
> +- Notification for new sign-ins to users' accounts feature becomes available
```suggestion
- Notification for new sign-ins to users' accounts feature becomes available.
```

2024-11-27 14:44 UTC, alexisintech commented on docs/backend-requests/versioning/available-versions.mdx
> +  - Instead of responding with a status of `needs_identifier`, the API now returns a status of `needs_first_factor`
```suggestion
  - Instead of responding with a status of `needs_identifier`, the API now returns a status of `needs_first_factor`.
```

2024-11-27 14:47 UTC, alexisintech requested changes
This file says its for API versions with their respective breaking changes - are these breaking changes?

Also, I'm not quite sure what versions we're documenting here. It goes from `2021-02-05` all the way to `2024-10-01`. Did someone advise you to add this to this document, or what was the reasoning leading up to this PR?

2024-11-27 15:06 UTC, Nikpolik commented
@alexisintech In this file we document the Client and Backend API versions and their changes. It was initially added as part of the API versioning project (by me 🙃).

This is actually the first api version (`2024-10-01`) we will ever release, but we needed to label how the API worked up to now, `2021-02-05` was chosen as the date that clerk was publicly released for the first time. That's why there is such a big jump in the versions. From now on I imagine there will be a smaller gap.

Regarding if the changes are breaking, the response change definitely is as we changed how the API behaves for the same input.

The new clients feature it's not exactly breaking but it will only work from this version and onward so it felt appropriate to mention it here.

For some additional context there is a ClerkJS pr that starts utilising this new version (and will link to this doc) 

- [Version bump](https://github.com/clerk/javascript/pull/4596/commits/4f447886ffb7d934e49b07ea9fe71be6f43bbd37)
- [Response changes](https://github.com/clerk/javascript/pull/4596/commits/11e2a6291e1f197f23753ff3ee2a4469b9cfdb2a#diff-9faac11c745dcb5c859887e17a0c93f4c5cc2d10756e2a952724ccfc250f9f2aR285-R294)

2024-11-27 17:04 UTC, alexisintech approved these changes
amazing, thank you providing more explanation and context!

2024-11-28 10:28 UTC, merged