[WIP] update: Mention `mutate` in useOrganizationList
clerk/clerk-docs pull request #310
Opened 2023-09-19 16:01 UTC by panteliselef

Please don't merge until the following is in prod release
https://github.com/clerkinc/javascript/pull/1745

2023-09-20 09:49 UTC, chanioxaris commented on docs/references/react/use-organization-list.mdx
> +              slug: 'random-org' + Date.now(),
We can omit slug here as it's optional and we are looking to phase it out as we are moving forward

2023-09-20 09:49 UTC, chanioxaris commented on docs/references/react/use-organization-list.mdx
> +              slug: 'random-org' + Date.now(),
Same here about the slug

2023-09-29 04:55 UTC, BRKalow commented on docs/references/react/use-organization-list.mdx
> +Under the hood, `useOrganizationList` is powered by SWR in order to support caching and pagination. Part of the return values from this hook are directly exported from useSWR and useSWRInfinite and y
```suggestion
Under the hood, `useOrganizationList` is powered by SWR in order to support caching and pagination. Part of the return values from this hook are directly exported from `useSWR` and `useSWRInfinite`, you can find more information in the [SWR documentation](https://swr.vercel.app/docs/getting-started)
```

2023-09-29 04:55 UTC, BRKalow commented on docs/references/react/use-organization-list.mdx
> +| `mutate` | A function for mutating the related cache for each paginated list. Also know as [Bound Mutate](https://swr.vercel.app/docs/mutation#bound-mutate). For more details about mutations please
```suggestion
| `mutate` | A function for mutating the related cache for each paginated list. Also known as [Bound Mutate](https://swr.vercel.app/docs/mutation#bound-mutate). For more details about mutations please visit the [SWR docs](https://swr.vercel.app/docs/mutation)
```

2023-11-14 19:10 UTC, alexisintech requested changes

2023-11-14 19:10 UTC, alexisintech commented on docs/references/react/use-organization-list.mdx
> +Under the hood, `useOrganizationList` is powered by SWR in order to support caching and pagination. Part of the return values from this hook are directly exported from useSWR and useSWRInfinite and y
```suggestion
Under the hood, `useOrganizationList` is powered by SWR in order to support caching and pagination. Part of the return values from this hook are directly exported from `useSWR` and `useSWRInfinite`. You can find more information in the [SWR documentation](https://swr.vercel.app/docs/getting-started).
```

2023-11-14 19:10 UTC, alexisintech commented on docs/references/react/use-organization-list.mdx
> +              slug: 'random-org' + Date.now(),
```suggestion
```

2023-11-14 19:10 UTC, alexisintech commented on docs/references/react/use-organization-list.mdx
> +              slug: 'random-org' + Date.now(),
```suggestion
```

2023-11-14 19:10 UTC, alexisintech commented on docs/references/react/use-organization-list.mdx
> +| `mutate` | A function for mutating the related cache for each paginated list. Also know as [Bound Mutate](https://swr.vercel.app/docs/mutation#bound-mutate). For more details about mutations please
```suggestion
| `mutate` | A function for mutating the related cache for each paginated list. Also known as [Bound Mutate](https://swr.vercel.app/docs/mutation#bound-mutate). You can find more information about mutations in the [SWR documentation](https://swr.vercel.app/docs/mutation).
```

2023-12-04 16:48 UTC, panteliselef commented
I am closing this. I will create a new PR in the coming weeks that will be up to date.

2023-12-04 16:48 UTC, closed without merging