(WIP) Added status information to both hooks
clerk/clerk-docs pull request #403
Opened 2023-10-08 01:55 UTC by royanger

2023-10-08 01:57 UTC, royanger commented
@BRKalow, I see that `abandoned` is a one of the statuses for useSignUp from https://github.com/clerkinc/javascript/blob/7f4d4b942e8834462cdc0976b106d9739c345f6b/packages/types/src/signUp.ts#L104, but I don't see how it is set. The only instances of 'abandoned' in the JS repo are types. Is this outdated, or set another way?

2023-11-03 13:03 UTC, rachelnabors approved these changes

2023-11-03 20:16 UTC, alexisintech requested changes

2023-11-03 20:16 UTC, alexisintech commented on docs/references/react/use-sign-in.mdx
> +| `needs_factor_two` | The Second Factor verification is missing. The Second Factor is a optional step to provide additional verification and includes `phone_code` and `totp`. See [Second Factor](/do
```suggestion
| `needs_factor_two` | The Second Factor verification is missing. The Second Factor is an optional step to provide additional verification and includes `phone_code` and `totp`. See [Second Factor](/docs/references/javascript/sign-in/second-factor) for details.|
```

2023-11-03 20:16 UTC, alexisintech commented on docs/references/react/use-sign-in.mdx
> +| `complete` | User has been signed in and custom flow can proceed to `setActive()` to create session. |
```suggestion
| `complete` | The user has been signed in and custom flow can proceed to `setActive()` to create session. |
```

2023-11-03 20:16 UTC, alexisintech commented on docs/references/react/use-sign-up.mdx
> +| `complete` | User has been created and custom flow can proceed to `setActive()` to create session. |
```suggestion
| `complete` | The user has been created and custom flow can proceed to `setActive()` to create session. |
```

2023-11-03 20:16 UTC, alexisintech commented on docs/references/react/use-sign-up.mdx
> +| `abandoned` | The SignUp attempt will be abandoned if it was started more than 24 hours previously. |
```suggestion
| `abandoned` | The sign-up attempt will be abandoned if it was started more than 24 hours previously. |
```

2023-11-03 20:16 UTC, alexisintech commented on docs/references/react/use-sign-up.mdx
> +| `missing_requirements` | A requirement from the [Email, Phone, Username](https://dashboard.clerk.com/last-active?path=user-authentication/email-phone-username) settings is missing. EG, in your Dash
```suggestion
| `missing_requirements` | A requirement from the [Email, Phone, Username](https://dashboard.clerk.com/last-active?path=user-authentication/email-phone-username) settings is missing. For example, in the Clerk Dashboard, the Password setting is required but a password was not provided in the custom flow. |
```

2023-11-06 21:21 UTC, BRKalow commented
@royanger This value comes from FAPI I believe, so we likely would not set it explicitly anywhere in our SDKs.

2023-11-06 21:25 UTC, royanger commented
> @royanger This value comes from FAPI I believe, so we likely would not set it explicitly anywhere in our SDKs.

I actually got Pantelis and Giannis to help out. Thanks for replying. https://clerkinc.slack.com/archives/C05LHV6AK50/p1698685499922449 I didn't add it to SignIn since its not in the type def.

2023-11-06 22:25 UTC, alexisintech approved these changes
😸💖

2023-11-15 01:10 UTC, merged