clarify on deprecated content
clerk/clerk-docs pull request #460
Opened 2023-11-02 22:04 UTC by alexisintech

This PR adds `<Callout />` components with `type="danger"` (instead of `type="info"`) to better highlight that something is deprecated. This PR also adds "(deprecated)" copy where necessary.

2023-11-03 13:16 UTC, rachelnabors requested changes
A vast improvement! (I would add a screenshot to this description of what the top of the pages look like for completeness, but not necessary at this stage.)

2023-11-03 13:16 UTC, rachelnabors commented on docs/references/javascript/organization/members.mdx
>    `GetMembershipsParams` was recently updated to `GetMembersParams`. The `limit` and `offset` parameters are now deprecated.
"recently" is an indefinite term. Can we provide a date?

2023-11-03 13:16 UTC, rachelnabors commented on docs/references/javascript/organization/organization.mdx
> +| `logoUrl` (deprecated) | `string \| null` | The full URL for the organization logo. (deprecated in favor of `imageUrl`) |
```suggestion
| `logoUrl` (deprecated) | `string \| null` | Deprecated in favor of `imageUrl`. |
```

2023-11-03 13:16 UTC, rachelnabors commented on docs/references/javascript/user/user.mdx
> +| `profileImageUrl` (deprecated) | `string \| null` | The URL for the user's profile image.<br />This property is deprecated in favor of `image_url`. |
```suggestion
| `profileImageUrl` (deprecated) | `string \| null` | Deprecated in favor of `image_url`. |
```

2023-11-03 13:16 UTC, rachelnabors commented on docs/references/javascript/user/user.mdx
> +| `password` (deprecated) | `string` | The user's password.<br />This property is deprecated. This will be removed in the next major version. Please use [`updatePassword(params)`](/docs/references/ja
What # is the next version?

2023-11-03 13:16 UTC, rachelnabors commented on docs/references/nextjs/with-clerk-middleware.mdx
>    `withClerkMiddleware()` is Clerk's previous middleware API and will soon be deprecated. Please use [`authMiddleware()`](/docs/references/nextjs/auth-middleware) going forward.
Can we give something more concrete than "soon?" A date, a release number, or just "an upcoming release"?

2023-11-06 22:24 UTC, jescalan approved these changes
🙌

2023-11-06 22:28 UTC, alexisintech commented
> A vast improvement! (I would add a screenshot to this description of what the top of the pages look like for completeness, but not necessary at this stage.)

I have to disagree and say that I feel like screenshots of every different page that I made changes to are not a good use of time. There are preview deployments that can be explored by the reviewers.

2023-11-07 15:18 UTC, JacobMGEvans approved these changes

2023-11-07 18:16 UTC, rachelnabors approved these changes

2023-11-07 18:16 UTC, merged