chore: Additions to styleguide
clerk/clerk-docs pull request #476
Opened 2023-11-08 12:39 UTC by LekoArts

Hi!

This adds "How to abbreviate a term" and some instructions about "Jargon" to the styleguide

2023-11-08 13:00 UTC, rachelnabors commented
I'm such a fan of the Google devs styleguide. These will be great additions!

2023-11-08 15:47 UTC, rachelnabors requested changes
Love it, a few suggestions!

2023-11-08 15:47 UTC, rachelnabors commented on STYLEGUIDE.md
> +> Clerk works great with progressive web apps (an app that's built using web platform technologies, but that provides a user experience like that of a platform-specific app) as it supports offline mo
```suggestion
> Clerk supports offline mode, a feature that lets users use an app without being connected to data or wifi. This means Clerk works great with progressive web apps, apps built with web platform technologies that provide similar experiences to platform-specific apps. You can use the [dynamic import pattern](https://www.patterns.dev/vanilla/dynamic-import) to improve loading speeds.
```

2023-11-09 00:39 UTC, rachelnabors commented on STYLEGUIDE.md
> +> An AST is a tree representation of code. ASTs are a fundamental part of the way a compiler works.
This is in the "don't" section!

2023-11-09 06:43 UTC, LekoArts commented on STYLEGUIDE.md
> +> An AST is a tree representation of code. ASTs are a fundamental part of the way a compiler works.
oh yeah, lol

2023-11-09 12:32 UTC, rachelnabors approved these changes

2023-11-09 12:34 UTC, merged