chore: Add deprecation for sms create to backend package
clerk/clerk-docs pull request #532
Opened 2023-12-07 11:59 UTC by Nikpolik

This endpoint was deprecated. Technically its still available in the backend package but with a warning that the endpoint is no longer working.

It will be completely removed in v5.

The Ruby SDK method was already marked as deprecated by @alexisintech 🙏 

I used almost the same message as a deprecation warning for `references/backend/overview`

Changes Made

- Removed examples of creating sms.
- Changed examples the included sms creation to now use email creation.
- Removed the `references/backend/sms-message/create-sms-message page`.
- Added a deprecation warning for createSMS in the  `references/backend/overview`.

2023-12-12 20:10 UTC, alexisintech requested changes

2023-12-12 20:10 UTC, alexisintech commented on docs/manifest.json
>        ],
Gives an error for trailing comma (causing build fail) 

```suggestion
      ]
```

2023-12-15 00:02 UTC, alexisintech approved these changes
😸

2023-12-15 13:43 UTC, rachelnabors commented
Is this ready for merge, @Nikpolik @alexisintech ?

2023-12-15 17:12 UTC, merged