Code review of PR-514
clerk/clerk-docs pull request #564
Opened 2023-12-13 20:33 UTC by alexisintech

[PR-514](https://github.com/clerk/clerk-docs/pull/514) was merged when V4 was merged, but still needed a review on its content.

2023-12-13 23:36 UTC, rachelnabors requested changes

2023-12-13 23:36 UTC, rachelnabors commented on docs/organizations/roles-permissions.mdx
> +### Default role
```suggestion
### Default roles
```

2023-12-14 16:41 UTC, alexisintech commented
Waiting on one last action item!

2023-12-15 22:15 UTC, alexisintech commented
Update 12/15/2023: action item is complete and that PR is merged. This PR is now all set to be merged!

2023-12-19 11:37 UTC, rachelnabors approved these changes
Adding image. Another PR solves the remaining task. Please merge!

2023-12-19 15:11 UTC, merged