webhook/route.ts Fix unsafe assignment of any value on payload
clerk/clerk-docs pull request #661
Opened 2024-01-26 23:51 UTC by jassibacha

After using the code provided on the [user db sync page](https://clerk.com/docs/users/sync-data#create-the-endpoint-in-your-application) in docs, I was hit with an **"Unsafe assignment of an `any` value."** error on the payload. Image attached.

![image](https://github.com/clerk/clerk-docs/assets/3331801/17d1f25a-b170-4089-806f-89c06a42953e)

Updating it to `const payload = (await req.json()) as Record<string, unknown>;` resolves this.

2024-01-30 21:45 UTC, jassibacha commented
Should mention that Dev Agrawal in the Discord replied to me saying this was happening because of differences in `tsconfig` and how strict the typescript rules are. He told me to add `as any` after `await req.json()`. I'd already tried that and it didn't work.

![image](https://github.com/clerk/clerk-docs/assets/3331801/937492c4-bc8a-4d15-b8d7-342e04c0a998)

Environment was setup with `create-t3-app@latest` about 2 weeks ago.

2024-01-30 21:49 UTC, royanger commented
Can you provide your Next version, @clerk/nextjs, typescript and anything else relevant in your setup @jassibacha? Thanks.

2024-01-31 01:53 UTC, jassibacha commented
For sure, here's `package.json` and `tsconfig.json`, as I mentioned this was generated with `create-t3-app@latest` about a week ago.

**package.json**:
```json
{
  "name": "beesly",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "next build",
    "db:push": "drizzle-kit push:mysql",
    "db:studio": "drizzle-kit studio",
    "dev": "next dev",
    "lint": "next lint",
    "start": "next start"
  },
  "dependencies": {
    "@clerk/clerk-react": "^4.30.3",
    "@clerk/nextjs": "^4.29.4",
    "@hookform/resolvers": "^3.3.4",
    "@planetscale/database": "^1.11.0",
    "@radix-ui/react-avatar": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-dropdown-menu": "^2.0.6",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-select": "^2.0.0",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-tabs": "^1.0.4",
    "@radix-ui/react-toast": "^1.1.5",
    "@t3-oss/env-nextjs": "^0.7.1",
    "@tanstack/react-query": "^4.36.1",
    "@trpc/client": "^10.43.6",
    "@trpc/next": "^10.43.6",
    "@trpc/react-query": "^10.43.6",
    "@trpc/server": "^10.43.6",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "cmdk": "^0.2.0",
    "date-fns": "^3.3.1",
    "drizzle-orm": "^0.29.3",
    "lucide-react": "^0.314.0",
    "next": "^14.0.4",
    "react": "18.2.0",
    "react-day-picker": "^8.10.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.49.3",
    "server-only": "^0.0.1",
    "superjson": "^2.2.1",
    "svix": "^1.15.0",
    "tailwind-merge": "^2.2.1",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@types/eslint": "^8.44.7",
    "@types/node": "^18.17.0",
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "@typescript-eslint/eslint-plugin": "^6.11.0",
    "@typescript-eslint/parser": "^6.11.0",
    "autoprefixer": "^10.4.14",
    "drizzle-kit": "^0.20.9",
    "eslint": "^8.54.0",
    "eslint-config-next": "^14.0.4",
    "mysql2": "^3.6.1",
    "postcss": "^8.4.31",
    "prettier": "^3.1.0",
    "prettier-plugin-tailwindcss": "^0.5.7",
    "tailwindcss": "^3.3.5",
    "typescript": "^5.1.6"
  },
  "ct3aMetadata": {
    "initVersion": "7.26.0"
  },
  "packageManager": "pnpm@8.14.0"
}
```

**tsconfig.json**:
```jsonc
{
  "compilerOptions": {
    /* Base Options: */
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "es2022",
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "isolatedModules": true,

    /* Strictness */
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "checkJs": true,

    /* Bundled projects */
    "lib": ["dom", "dom.iterable", "ES2022"],
    "noEmit": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "jsx": "preserve",
    "plugins": [{ "name": "next" }],
    "incremental": true,

    /* Path Aliases */
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    ".eslintrc.cjs",
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "**/*.cjs",
    "**/*.js",
    ".next/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
```

2024-02-06 18:52 UTC, JacobMGEvans commented
Though `const payload = (await req.json()) as Record<string, unknown>;` silences your linter error/warning it is ostensibly the same as the inferred `any` because you are raw casting to a Generic/Utility type. 

If this is something you want to handle a bit better, my suggestion is using a package like [Zod](https://github.com/colinhacks/zod) or using [TypeScript predicate assertion](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) functions which you can do type guarding inside the function with:
```ts
function isFish(object: undefined | Stuff) object is Stuff {
if(do some checks against object) return true 

return false 
}
```

2024-02-06 18:54 UTC, JacobMGEvans requested changes
see previous comment.

2024-03-05 21:46 UTC, alexisintech commented
@JacobMGEvans @royanger I'd like to close this ticket out as it's getting stale. were either of you open to correcting the docs and making these changes? or possibly collaborating with me to get it done as I'm not too familiar with webhooks! (let's hop on a call)

2024-03-26 21:14 UTC, royanger commented
Circling back here to look this over, I think that the correct fix is `unknown`, which is accurate. At that line, the type is unknown. After the .verify() further down, it will be a `WebhookEvent`, and then correct types for the events can be inferred. 

I've submitted a separate PR with this change, and a few changes to the Sync guide and a new debugging guide. See https://github.com/clerk/clerk-docs/pull/851 This PR can probably be closed.

Thanks @jassibacha for calling this out.

2024-03-27 21:25 UTC, closed without merging