Update auth-middleware.mdx
clerk/clerk-docs pull request #709
Opened 2024-02-16 19:13 UTC by shawnesquivel

typo on behavior
add comma to make code syntactically correct

2024-02-16 19:21 UTC, alexisintech requested changes

2024-02-16 19:21 UTC, alexisintech commented on docs/references/nextjs/auth-middleware.mdx
> +If there is no `afterAuth` present in the middleware, then `authMiddleware` will fall back to its default behaviour. The default behaviour is:
```suggestion
If there is no `afterAuth` present in the middleware, then `authMiddleware` will fall back to its default behavior. The default behavior is:
```

2024-02-16 19:36 UTC, S3Prototype commented on docs/references/nextjs/auth-middleware.mdx
> +If there is no `afterAuth` present in the middleware, then `authMiddleware` will fall back to its default behavior. The default behavior is:
```suggestion
If there is no `afterAuth` present in the middleware, then `authMiddleware` will fall back to its default behavior:
```

2024-02-16 19:36 UTC, S3Prototype approved these changes
Approved with one suggested change 👍

2024-02-16 20:47 UTC, shawnesquivel reviewed
added requested changes

2024-02-20 23:13 UTC, alexisintech approved these changes
thanks so much for the contribution 😸💖

2024-02-20 23:13 UTC, merged

2024-02-20 23:21 UTC, shawnesquivel commented
> thanks so much for the contribution 😸💖

My pleasure!