DOCS-5432 add section about oauth access token
clerk/clerk-docs pull request #786
Opened 2024-03-07 15:55 UTC by alexisintech

2024-03-07 16:06 UTC, jescalan requested changes
This is good! Just a couple comments

2024-03-07 16:06 UTC, jescalan commented on docs/authentication/social-connections/oauth.mdx
> +To query an OAuth progvider for additional data of your users, you can use the OAuth access token.
```suggestion
You can use a provider's OAuth access token to access user data from that provider in addition to their data from Clerk.
```

2024-03-07 16:06 UTC, jescalan commented on docs/authentication/social-connections/oauth.mdx
> +To retrieve the OAuth access token for a user, use the `getUserOauthAccessToken()` method from the Clerk Backend SDK. Note that this method must be used in a server environment, and cannot be run on
We should link to the page for it here

2024-03-07 20:00 UTC, alexisintech commented on docs/authentication/social-connections/oauth.mdx
> +Social connections provide better security than passwords and other long-lived knowledge-based secrets. With social connections, users gain frictionless access to your application by using their exis
I have no clue who wrote this LMAO I can remove it though o.O

2024-03-07 20:00 UTC, alexisintech commented on docs/authentication/social-connections/oauth.mdx
> +To retrieve the OAuth access token for a user, use the `getUserOauthAccessToken()` method from the Clerk Backend SDK. Note that this method must be used in a server environment, and cannot be run on
oh I'm silly I forgot that

2024-03-07 22:21 UTC, alexisintech commented on docs/authentication/social-connections/oauth.mdx
> +Clerk ensures that the OAuth Access Token will be always fresh so that you don't have to worry about OAuth Refresh Tokens anymore.
added!

2024-03-08 01:15 UTC, jescalan approved these changes
This is 🌟

2024-03-08 01:15 UTC, jescalan commented on docs/authentication/social-connections/oauth.mdx
> +```
😍

2024-03-08 14:55 UTC, merged