Add Environment Variables page
clerk/clerk-docs pull request #885
Opened 2024-04-08 14:54 UTC by S3Prototype

This PR:

- Adds a dedicated clerk environment variables page

2024-04-10 19:25 UTC, alexisintech requested changes

2024-04-10 19:25 UTC, alexisintech commented on docs/references/javascript/clerk/handle-navigation.mdx
> +| `afterSignInUrl` | `string \| undefined \| null` | Full URL or path to navigate after successful sign in. Defaults to `/`. Use [the environment variable](/docs/deployments/clerk-environment-variabl
```suggestion
| `afterSignUpUrl` | `string \| undefined \| null` | Full URL or path to navigate after successful sign up. Defaults to `/`. It's recommended to use [the environment variable](/docs/deployments/clerk-environment-variables#sign-in-and-sign-up-redirects) instead. |
| `afterSignInUrl` | `string \| undefined \| null` | Full URL or path to navigate after successful sign in. Defaults to `/`. It's recommended to use [the environment variable](/docs/deployments/clerk-environment-variables#sign-in-and-sign-up-redirects) instead. |
```

2024-04-10 19:25 UTC, alexisintech commented on docs/references/javascript/types/sign-in-redirect-options.mdx
> +| `afterSignUpUrl?` | `string \| null \| undefined` | Full URL or path to navigate after successful sign-up. Defaults to `/`. Use [the environment variable](/docs/deployments/clerk-environment-variab
```suggestion
| `afterSignInUrl?` | `string \| null \| undefined` | Full URL or path to navigate after successful sign-in. Defaults to `/`. It's recommended to use [the environment variable](/docs/deployments/clerk-environment-variables#sign-in-and-sign-up-redirects) instead. |
| `afterSignUpUrl?` | `string \| null \| undefined` | Full URL or path to navigate after successful sign-up. Defaults to `/`. It's recommended to use [the environment variable](/docs/deployments/clerk-environment-variables#sign-in-and-sign-up-redirects) instead. |
```

2024-04-10 19:25 UTC, alexisintech commented on docs/references/javascript/types/sign-up-redirect-options.mdx
> +| `afterSignUpUrl?` | `string \| null \| undefined` | Full URL or path to navigate after successful sign-up. Defaults to `/`. Use [the environment variable](/docs/deployments/clerk-environment-variab
```suggestion
| `afterSignInUrl?` | `string \| null \| undefined` | Full URL or path to navigate after successful sign-in. Defaults to `/`. It's recommended to use [the environment variable](/docs/deployments/clerk-environment-variables#sign-in-and-sign-up-redirects) instead. |
| `afterSignUpUrl?` | `string \| null \| undefined` | Full URL or path to navigate after successful sign-up. Defaults to `/`. It's recommended to use [the environment variable](/docs/deployments/clerk-environment-variables#sign-in-and-sign-up-redirects) instead. |
```

2024-04-10 19:25 UTC, alexisintech commented on docs/references/nextjs/current-user.mdx
this page should not be getting reverted

2024-04-10 19:25 UTC, alexisintech commented on docs/testing/test-emails-and-phones.mdx
this page should not be getting reverted.

2024-04-11 12:54 UTC, S3Prototype commented on docs/references/backend/overview.mdx
rebase error

2024-04-12 16:08 UTC, merged